[project]
name = "lde-glance"
description = ""
readme = "README.md"
dynamic = ['version']
requires-python = ">=3.10"
authors = [{name="Blue Yonder GmbH"}]
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
]

[tool.setuptools]
py-modules = ["glance", "glance_web", "glance_pluggins"]